config/routes.rb
Rails.application.routes.draw do


  resources :taggings
  resources :user_channels
  resources :messages
  # devise_for :users, class_name: "Admin::User"

  mount ActionCable.server => '/cable'

  scope '/admin' do

    devise_for :admin_users,
               :class_name  => "Admin::User",
               :path        => '',
               :controllers => {
                   :sessions      => "admin/sessions",
                   :invitations => 'admin/invitations',
               }
    get '/' => 'admin/homes#dashboard'
  end



  namespace :admin  do
    resources :channels
    resources :rooms
  end

  root 'home#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :categories
  resources :exchanges
  resources :channels do
    member do
    get 'update_channel_message'
    end
  end

  resources :messages
  resources :rooms
  resources :conversations do
    member do
      get 'update_conversation_message'
    end

  end

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  has_many :messages, as: :messageable

  validates :first_user_id, :uniqueness => {:scope => :second_user_id}
  belongs_to :first_user, :class_name => 'User', :foreign_key => 'first_user_id'
  belongs_to :second_user , :class_name => 'User', :foreign_key => 'second_user_id'
  scope :first_or_second, -> (first_id , second_id) { where(first_user_id: first_id , second_user_id: second_id) }
  validate :uniqueness_of_conversation

  def uniqueness_of_conversation
    if Conversation.where(first_user_id: self.first_user_id , second_user_id: self.second_user_id ).present? || Conversation.where(first_user_id: self.second_user_id , second_user_id: self.first_user_id ).present?
    errors.add(:first_user_id, "some error")
    end
  end

  def conversation_reciver(user_id)
    if self.first_user.id == user_id
    return second_user
    else
      return first_user
    end
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: [:show, :edit, :update, :destroy ,:update_conversation_message]

  # GET /conversations
  # GET /conversations.json
  def index
    @conversations = Conversation.all
  end

  # GET /conversations/1
  # GET /conversations/1.json


  def show
    @unread_message_count = @conversation.messages.unread_message(current_user.id).count
    @unread_message_coun = @unread_message_count
    if @unread_message_count != 0
      if @unread_message_count <= 5
        sum_unred = 6 - @unread_message_count
        @unread_message_coun = @unread_message_count + sum_unred
      elsif @unread_message_count >= 6
        @unread_message_coun = @unread_message_count + 1
      end
      @conversation_messages  = @conversation.messages.paginate(page: params[:page] ,per_page: @unread_message_coun)
    else
      @conversation_messages = @conversation.messages.paginate(page: params[:page],per_page: 6)
    end
  end

  # GET /conversations/new
  def new
    @conversation = Conversation.new
  end

  # GET /conversations/1/edit
  def edit
  end

  def update_conversation_message

    if (@conversation.messages.present? && @conversation.messages.unread_message(current_user.id).count != 0)
      Message::ReadAllUnreadMessage.perform_now(@conversation.messages.first , current_user.id)
    end

  end

  # POST /conversations
  # POST /conversations.json
  def create
    @conversation = Conversation.new(conversation_params)

    respond_to do |format|
      if @conversation.save
        format.html { redirect_to @conversation, notice: 'Conversation was successfully created.' }
        format.json { render :show, status: :created, location: @conversation }
      else
        format.html { render :new }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conversations/1
  # PATCH/PUT /conversations/1.json
  def update
    respond_to do |format|
      if @conversation.update(conversation_params)
        format.html { redirect_to @conversation, notice: 'Conversation was successfully updated.' }
        format.json { render :show, status: :ok, location: @conversation }
      else
        format.html { render :edit }
        format.json { render json: @conversation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conversations/1
  # DELETE /conversations/1.json
  def destroy
    @conversation.destroy
    respond_to do |format|
      format.html { redirect_to conversations_url, notice: 'Conversation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conversation
      @conversation = Conversation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def conversation_params
      params.require(:conversation).permit(:name, :first_user_id, :second_user_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_form.html.erb
<%= simple_form_for(@conversation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :first_user_id %>
    <%= f.input :second_user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/conversations/_js.html.erb
<script>
  $(document).ready(function(){
    <% if @unread_message_count != 0 %>
    var unread = <%= @unread_message_count %>
            setTimeout(function() {
              $.ajax({
                type: 'get',
                url: '/conversations/'+ <%= @conversation.id  %>+'/update_conversation_message' ,
                dataType:'script',
                success:function(data){

                  $('#loader').hide();
                  setTimeout(function() {
                    $("#conversation_count"+<%= @conversation.id %>).text($("#conversation_count"+<%= @conversation.id %>).text() - unread);
                    $("#unread_message_div_count").fadeOut( "slow" );
                  }, 1000);
                },
                error:function(data){
                  console.log(data);
                }
              });
            }, 2000);
    <% end %>


    if ($('#paginate-load-more-button').length > 0) {
      $('#paginate-load-more-button .pagination').hide();


      <% if @unread_message_count == 0 %>
      $('#chat_content_scroll').scrollTop($('#chat_content_scroll')[0].scrollHeight);
      <% else %>
      $('#chat_content_scroll').scrollTop(65);
      <% end %>


      $('#chat_content_scroll').scroll(function(){
        if ($('#chat_content_scroll').scrollTop() == 0 && $('#paginate-load-more-button').length > 0){
          $('#loader').show();
          setTimeout(function(){
            more_posts_url = $('#paginate-load-more-button .pagination .next_page ').attr('href');
            $this = $(this);
            $.getScript(more_posts_url, function() {
              if ($this) {
                $('#loader').hide();
              }
            });
          },500);
        }
      });
    };


    $("#chat_text_field").mention({

      users: [
        <% Room.all.each do |room| %>
        {
          name: '<%= room.name %>',
          username: '<%=  room.name %>'
        },
        <% end %>

        <% Channel.all.each do |channel| %>
        {
          name: '<%= channel.name %>',
          username: '<%=  channel.name %>'
        },
        <% end %>


      ]
    });


  });
</script>

app/views/conversations/_message_pannel.html.haml
- @conversation_messages.each do |message|
  .row.flex-nowrap.message-row.contact.p-4
    - if message.created_by.image_url.present?
      = image_tag message.created_by.image_url , class: "avatar mr-4"
    - else
      = image_tag "profile.jpg" , class: "avatar mr-4"
    .bubble.ow
      %b{style: "color: black;"}
        = message.created_by.full_name
      .message{style:"line-height: 1;  white-space: normal;"}
        = message.message_text
      .time.text-muted.text-right.mt-2
        = message.created_at.strftime("%Y-%d-%m %H:%m")

app/views/conversations/edit.html.erb
<h1>Editing Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Show', @conversation %> |
<%= link_to 'Back', conversations_path %>

app/views/conversations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Conversations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>First user</th>
      <th>Second user</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @conversations.each do |conversation| %>
      <tr>
        <td><%= conversation.name %></td>
        <td><%= conversation.first_user_id %></td>
        <td><%= conversation.second_user_id %></td>
        <td><%= link_to 'Show', conversation %></td>
        <td><%= link_to 'Edit', edit_conversation_path(conversation) %></td>
        <td><%= link_to 'Destroy', conversation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Conversation', new_conversation_path %>

app/views/conversations/new.html.erb
<h1>New Conversation</h1>

<%= render 'form', conversation: @conversation %>

<%= link_to 'Back', conversations_path %>

app/views/conversations/show.html.haml
#chat.page-layout.carded.full-width
  .top-bg.bg-secondary
  .page-content.w-100.mx-auto.px-0.pt-0.px-sm-4.pt-sm-8
    .page-content-card.row.no-gutters
      .content.col
        #chat-content-views.views
          #loader
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .lading
          #chat-view.view.flex-column.align-items-center.justify-content-center.d-flex
            .toolbar.row.no-gutters.align-items-center.justify-content-between.w-100.px-4.conversation_id{id: "conversation#{@conversation.id}" ,"data-conversation-id" => "#{@conversation.id}"}
              .col
                .row.no-gutters.align-items-center
                  .chat-contact.row.no-gutters.align-items-center
                    .avatar-wrapper.mr-4
                      - if @conversation.conversation_reciver(current_user.id).image_url.present?
                        = image_tag @conversation.conversation_reciver(current_user.id).image_url , class: "avatar"
                      - else
                        = image_tag "profile.jpg" , class: "avatar"
                      %i.icon.icon-.s-4.statu
                    .chat-contact-name
                      = @conversation.conversation_reciver(current_user.id).full_name
            .chat-content.col.custom-scrollbar#chat_content_scroll
              - if @conversation_messages.next_page
                #paginate-load-more-button
                  = will_paginate @conversation_messages
              .chat-messages#chat_append_div
                - first = 0
                - @conversation_messages.reverse.each do |message|
                  - if @unread_message_count != 0 && @conversation_messages.unread_message(current_user.id).last == message && first == 0
                    .divider#unread_message_div_count{style: "margin-top: 5%;"}
                      %span.float-right
                        new message
                      - first = 1
                  .row.flex-nowrap.message-row.contact.p-4{class: "#{@conversation_messages.first == message ? "last_message" : ""}"}
                    - if message.created_by.image_url.present?
                      = image_tag message.created_by.image_url , class: "avatar mr-4"
                    - else
                      = image_tag "profile.jpg" , class: "avatar mr-4"
                    .bubble.ow
                      %b{style: "color: black;"}
                        = message.created_by.full_name
                      .message{style:"line-height: 1;  white-space: normal;"}
                        = message.message_text
                      .time.text-muted.text-right.mt-2
                        = message.created_at.strftime("%Y-%d-%m %H:%m")
            .chat-footer.row.align-items-center.justify-content-center.w-100.p-2.pl-4
              = form_for Message.new , remote: true , html: { class: "reply-form row no-gutters align-items-center w-100" } do |f|
                .form-group.col.mr-4
                  = f.text_field :message_text , class:"form-control"   , id: "chat_text_field" ,placeholder: "Type and hit enter to send message"
                  = f.hidden_field :created_by_id , value: current_user.id
                  = f.hidden_field :messageable_id , value: @conversation.id
                  = f.hidden_field :messageable_type , value: "Conversation"
                  %input{:name => "message[unread_message_by_user][]", :type => "hidden", :value => "#{@conversation.first_user == current_user ? @conversation.second_user.id : @conversation.first_user.id}"}/
                %button.btn.btn-fab.btn-secondary{"aria-label" => "Send message", :type => "submit"}
                  %i.icon.icon-send
                  = render 'conversations/js'

:javascript

  $( document ).ready(function() {



    $("#chat_text_field").emojiPicker();

    $('.emojiPickerIcon').trigger('click');

    $('#loader').hide();


    $(document).click(function() {
      setTimeout(function() {
        update_conversation()
      }, 1000);
    });





    function update_conversation() {
    $.ajax({
        type: 'get',
        url: '/conversations/'+ $('.conversation_id').data('conversation-id') +'/update_conversation_message' ,
        dataType:'script',
        success:function(data){

          $('#loader').hide();
          setTimeout(function() {
          }, 1000);
        },
        error:function(data){
          console.log(data);
        }
      });
    }

  });

app/views/conversations/show.js.erb
var firstMsg = $('.message-row:first');
var curOffset = firstMsg.offset().top - $('#chat_content_scroll').scrollTop() ;
curOffset = curOffset + 70;

$('#chat_append_div').prepend("<%= escape_javascript(render 'message_pannel' ) %>");
<% if @conversation_messages.next_page %>
$('#paginate-load-more-button .pagination').replaceWith("<%= j will_paginate @conversation_messages %>");
$('#paginate-load-more-button .pagination').hide();

$('#chat_content_scroll').scrollTop(firstMsg.offset().top-curOffset );

<% else %>
$('#paginate-load-more-button').remove();
<% end %>