config/routes.rb
Rails.application.routes.draw do


  resources :taggings
  resources :user_channels
  resources :messages
  # devise_for :users, class_name: "Admin::User"

  mount ActionCable.server => '/cable'

  scope '/admin' do

    devise_for :admin_users,
               :class_name  => "Admin::User",
               :path        => '',
               :controllers => {
                   :sessions      => "admin/sessions",
                   :invitations => 'admin/invitations',
               }
    get '/' => 'admin/homes#dashboard'
  end



  namespace :admin  do
    resources :channels
    resources :rooms
  end

  root 'home#index'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :categories
  resources :exchanges
  resources :channels do
    member do
    get 'update_channel_message'
    end
  end

  resources :messages
  resources :rooms
  resources :conversations do
    member do
      get 'update_conversation_message'
    end

  end

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :channels

  enum status: [ :active, :archived ]
  accepts_nested_attributes_for :channels, reject_if: :all_blank, allow_destroy: true

  validates :name, :presence => true
  validates :description, :presence => true
  validates :image_url, :presence => true

  after_create :create_general_channel_for_room

  def create_general_channel_for_room
    Channel.create(name: "general" , description: "This is a general Channel" , image_url: "https://cdn.filestackcontent.com/8T0UhvUyTByH5WPRIbYu" , room_id: self.id)
  end


  def  unread_channel_message_count(user_id)

    count = 0
    self.channels.each do |channel|
    count = channel.messages.unread_message(user_id).count + count
    end

    return count
  end



end

app/controllers/admin/rooms_controller.rb
class Admin::RoomsController < Admin::AdminController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new()
    @room.channels.build
  end

  # POST /channels
  # POST /channels.json
  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Channel was successfully created.' }
        format.json { render :show, status: :created, location: @room }
        format.js {}
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  def edit

    if @room.channels.empty?
      @room.channels.build
    end

  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Channel was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
        format.js {}
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
        format.js {}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def room_params
    params.require(:room).permit(:name, :description, :image_url, :status , channels_attributes: [:id, :description, :name,:image_url ,:_destroy])
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  def show
    @first_channel = @room.channels.includes(:messages).first
     @unread_message_count = @first_channel.messages.unread_message(current_user.id).count
    @unread_message_coun = @unread_message_count
    if @unread_message_count != 0
      if @unread_message_count <= 5
        sum_unred = 6 - @unread_message_count
        @unread_message_coun = @unread_message_count + sum_unred
      elsif @unread_message_count >= 6
        @unread_message_coun = @unread_message_count + 1
      end
      @first_channel_messages  = @first_channel.messages.paginate(page: params[:page] ,per_page: @unread_message_coun)
    else
      @first_channel_messages = @first_channel.messages.paginate(page: params[:page],per_page: 6)
    end
  end

  def new
    @room = Room.new
  end

  def edit

  end

  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.includes(:channels).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :image_url, :status)
    end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :image_url %>
    <%= f.input :status %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/_js.html.erb
<script>
  $(document).ready(function(){

    $('#loader').hide();
    $('.chat-list .contact').on('click', function ()
    {
      $('#loader').show();
      console.log($(this).attr('id'));
      $.ajax({
        type: 'get',
        url: '/channels/'+$(this).attr('id') ,
        dataType:'script',
        success:function(data){
          console.log(data);
          $('#loader').hide();
        },
        error:function(data){
          console.log(data);
        }
      });
    });



    <% if @unread_message_count != 0 %>
    var unread = <%= @unread_message_count %>
    setTimeout(function() {
      $.ajax({
        type: 'get',
        url: '/channels/'+ <%= @first_channel.id  %>+'/update_channel_message' ,
        dataType:'script',
        success:function(data){
          console.log(data);
          $('#loader').hide();
          setTimeout(function() {
            $("#channel_count"+<%= @first_channel.id %>).text("0");
            $("#channel_room_id"+<%= @first_channel.room.id %>).text($("#channel_room_id"+<%= @first_channel.room.id %>).text() - unread);
            $("#unread_message_div_count").fadeOut( "slow" );
            $("#tagging_room"+<%= @first_channel.room.id %>).fadeOut( "slow" );
            $("#tagging_channel"+<%= @first_channel.id %>).fadeOut( "slow" );


          }, 1000);
        },
        error:function(data){
          console.log(data);
        }
      });
    }, 2000);
    <% end %>

    if ($('#paginate-load-more-button').length > 0) {
      $('#paginate-load-more-button .pagination').hide();

      <% if @unread_message_count == 0 %>
      $('#chat_content_scroll').scrollTop($('#chat_content_scroll')[0].scrollHeight);
      <% else %>
      $('#chat_content_scroll').scrollTop(65);
      <% end %>

      $('#chat_content_scroll').scroll(function(){
        if ($('#chat_content_scroll').scrollTop() == 0 && $('#paginate-load-more-button').length > 0){
          $('#loader').show();
          setTimeout(function(){
            more_posts_url = $('#paginate-load-more-button .pagination .next_page ').attr('href');
            $this = $(this);
            $.getScript(more_posts_url, function() {
              if ($this) {
                $('#loader').hide();
              }
            });
          },500);
        }
      });
    };

    $("#chat_text_field").mention({
      users: [
        <% @first_channel.users.all.each do |user| %>
        {
          name: '<%= user.full_name %>',
          username: '<%=  user.user_name%> '
        },
        <% end %>
      ]
    });

    $("#chat_text_field").emojiPicker();




  });
</script>

app/views/rooms/_message_pannel.html.haml
- @first_channel_messages.each do |message|
  .row.flex-nowrap.message-row.contact.p-4
    - if message.created_by.image_url.present?
      = image_tag message.created_by.image_url , class: "avatar mr-4"
    - else
      = image_tag "profile.jpg" , class: "avatar mr-4"
    .bubble.ow
      %b{style: "color: black;"}
        = message.created_by.full_name
      .message{style:"line-height: 1;  white-space: normal;"}
        = message.message_text
      .time.text-muted.text-right.mt-2
        = message.created_at.strftime("%Y-%d-%m %H:%m")

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.image_url %></td>
        <td><%= room.status %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.haml
#chat.page-layout.carded.full-width
  .top-bg.bg-secondary
  .page-content.w-100.mx-auto.px-0.pt-0.px-sm-4.pt-sm-8
    .page-content-card.row.no-gutters
      %aside.left-sidebar{"data-fuse-bar" => "chat-left-sidebar", "data-fuse-bar-media-step" => "lg"}
        #chat-left-sidebar-views.views
          #chats-view.view.d-flex.flex-column.no-gutters
            .toolbar
              .toolbar-top.row.no-gutters.align-items-center.justify-content-between.px-4
                .avatar-wrapper
                  = image_tag @room.image_url , class: "avatar"
                  %i.icon-.status.online.s-4
                %button.btn.btn-icon{:type => "button"}
                  %i.icon.icon-dots-vertical
              .toolbar-bottom.row.align-items-center.no-gutters.px-4
                .search-wrapper.md-elevation-1.row.no-gutters.align-items-center.w-100.p-2
                  %i.icon-magnify.s-4
                  %input.col.pl-2{:placeholder => "Search or start new chat", :type => "text"}/
            .content.col.custom-scrollbar
              .chat-list
                .contact.ripple.flex-wrap.flex-sm-nowrap.row.p-4.no-gutters.align-items-center{:id => "#{@first_channel.id}"}
                  .col-auto.avatar-wrapper
                    = image_tag @first_channel.image_url , class: "avatar"
                  .col.px-4
                    %span.name.h6
                      = @first_channel.name
                    %p.last-message.text-truncate.text-muted
                      = @first_channel.description
                    %p.last-message.text-truncate.text-muted
                      members: #{@first_channel.users.count }
                  %i.icon-at.float-right.at_rate{id: "tagging_channel#{@first_channel.id}" , style: " margin-top: 27px; margin-right: -27px; visibility: #{current_user.taggings.channel_tagging(@first_channel.id).un_read.count >= 1 ? 'visible': 'hidden'}"}
                  .col-12.col-sm-auto.d-flex.flex-column.align-items-end
                    .last-message-time
                      = @first_channel.created_at.strftime("%d/%m/%y")
                    .bg-secondary.text-auto.unread-message-count.mt-2{id: "channel_count#{@first_channel.id}"}
                      = @first_channel.messages.unread_message(current_user.id).count
                .divider
                - @room.channels.each do |channel|
                  - next if channel.id == @first_channel.id
                  .contact.ripple.flex-wrap.flex-sm-nowrap.row.p-4.no-gutters.align-items-center{:id => "#{channel.id}"}
                    .col-auto.avatar-wrapper
                      = image_tag channel.image_url , class: "avatar"
                    .col.px-4
                      %span.name.h6
                        = channel.name
                      %p.last-message.text-truncate.text-muted
                        = channel.description
                      %p.last-message.text-truncate.text-muted
                        members: #{channel.users.count }
                    %i.icon-at.float-right.at_rate{id: "tagging_channel#{channel.id}" , style: " margin-top: 27px; margin-right: -27px; visibility: #{current_user.taggings.channel_tagging(channel.id).un_read.count >= 1 ? 'visible': 'hidden'}"}
                    .col-12.col-sm-auto.d-flex.flex-column.align-items-end
                      .last-message-time
                        = channel.created_at.strftime("%d/%m/%y")
                      .bg-secondary.text-auto.unread-message-count.mt-2{id: "channel_count#{channel.id}"}
                        = channel.messages.unread_message(current_user.id).count
                  .divider
      .content.col
        #chat-content-views.views
          #start-view.view.flex-column.align-items-center.justify-content-center{class: "#{current_user.is_user_channel?(@first_channel.id) ? "d-none" : "d-flex"}"}
            .big-circle.md-elevation-4.row.align-items-center.justify-content-center.no-gutters
              %i.s-32.text-secondary.icon-hangouts
            %span.app-title.h3.my-3
              = @first_channel.name.titleize
            %span.text-muted.h6.d-none.d-xl-block Join channel to start the chat!..
            = link_to "Join Channel", user_channels_path(authenticity_token: form_authenticity_token, user_channel: {user_id: current_user.id , channel_id: @first_channel.id   }), method: :post ,:remote => true  , class: "btn btn-secondary fuse-ripple-ready"
          #loader
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .dot
            .lading
          #chat-view.view.flex-column.align-items-center.justify-content-center{class: "#{current_user.is_user_channel?(@first_channel.id) ? "d-flex" : "d-none"}"}
            .toolbar.row.no-gutters.align-items-center.justify-content-between.w-100.px-4.channel_id{id: "channel#{@first_channel.id}" ,"data-channel-id" => "#{@first_channel.id}"}
              .col{id: "user#{current_user.id}"}
                .row.no-gutters.align-items-center
                  .chat-contact.row.no-gutters.align-items-center
                    .avatar-wrapper.mr-4
                      = image_tag @first_channel.image_url , class: "avatar"
                      %i.icon.icon-.s-4.status.online
                    .chat-contact-name
                      = @first_channel.name
            .chat-content.col.custom-scrollbar#chat_content_scroll{style: "overflow-y:scroll;"}
              - if @first_channel_messages.next_page
                #paginate-load-more-button
                  = will_paginate @first_channel_messages
              .chat-messages#chat_append_div
                - first = 0
                - @first_channel_messages.reverse.each do |message|
                  - if @unread_message_count != 0 && @first_channel_messages.unread_message(current_user.id).last == message && first == 0
                    .divider#unread_message_div_count{style: "margin-top: 5%;"}
                      %span.float-right
                        new message
                      - first = 1
                  .row.flex-nowrap.message-row.contact.p-4{class: "#{@first_channel_messages.first == message ? "last_message" : ""}"}
                    - if message.created_by.image_url.present?
                      = image_tag message.created_by.image_url , class: "avatar mr-4"
                    - else
                      = image_tag "profile.jpg" , class: "avatar mr-4"
                    .bubble.ow
                      %b{style: "color: black;"}
                        = message.created_by.full_name
                      .message{style:"line-height: 1;  white-space: normal;"}
                        = message.message_text
                      .time.text-muted.text-right.mt-2
                        = message.created_at.strftime("%Y-%d-%m %H:%m")
            .chat-footer.row.align-items-center.justify-content-center.w-100.p-2.pl-4
              = form_for Message.new , remote: true , html: { class: "reply-form row no-gutters align-items-center w-100" } do |f|
                .form-group.col.mr-4
                  = f.text_field :message_text , class:"form-control emojiable-option" , id: "chat_text_field"  ,placeholder: "Type and hit enter to send message"
                  = f.hidden_field :created_by_id , value: current_user.id
                  = f.hidden_field :messageable_id , value: @first_channel.id
                  = f.hidden_field :messageable_type , value: "Channel"
                %button.btn.btn-fab.btn-secondary{"aria-label" => "Send message", :type => "submit"}
                  %i.icon.icon-send
                  = render 'rooms/js'
:javascript

  $( document ).ready(function() {

      $('.emojiPickerIcon').trigger('click');



    $(document).click(function() {
      setTimeout(function() {
        update_channel()
      }, 1000);
    });

    function update_channel() {
    $.ajax({
        type: 'get',
        url: '/channels/'+ $('.channel_id').data('channel-id') +'/update_channel_message' ,
        dataType:'script',
        success:function(data){
          console.log(data);
          $('#loader').hide();
          setTimeout(function() {
          }, 1000);
        },
        error:function(data){
          console.log(data);
        }
      });
    }
   });

app/views/rooms/show.js.erb
var firstMsg = $('.message-row:first');
var curOffset = firstMsg.offset().top - $('#chat_content_scroll').scrollTop() ;
curOffset = curOffset + 70;

$('#chat_append_div').prepend("<%= escape_javascript(render 'message_pannel' ) %>");
<% if @first_channel_messages.next_page %>
$('#paginate-load-more-button .pagination').replaceWith("<%= j will_paginate @first_channel_messages %>");
$('#paginate-load-more-button .pagination').hide();

$('#chat_content_scroll').scrollTop(firstMsg.offset().top-curOffset );

<% else %>
$('#paginate-load-more-button').remove();
<% end %>